# MOdel Testing

In [3]:
import pickle
import  json
import numpy as np
import pandas as pd


In [5]:
with open('linear_regression.pkl','rb') as f:
    linear_model = pickle.load(f)


linear_model

LinearRegression()

In [6]:
with open("label_enc_data.json",'rb') as f:
    column_data  = json.load(f)

column_data

{'smoker': {'no': 0, 'yes': 1}, 'gender': {'male': 1, 'female': 0}}

In [9]:
column_names = linear_model.feature_names_in_
column_names

array(['age', 'gender', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype=object)

In [11]:
len(column_names)

9

# USER

In [13]:
age = 35
gender = 'male'
bmi = 26.9
children  = 2
smoker = 'no'
region = 'southeast'

In [15]:
# test_array = np.zeros((len(column_names),ndim )
test_array = np.zeros((1,len(column_names)))
test_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:


test_array[0,0] = age # 34
test_array[0,1] = column_data['gender'][gender]
test_array[0,2] = bmi
test_array[0,3] = children
test_array[0,4] = column_data['smoker'][smoker]

region = 'southeast'
region = f"region_{region}"
region

'region_southeast'

In [19]:
test_array

array([[35. ,  1. , 26.9,  2. ,  0. ,  0. ,  0. ,  0. ,  0. ]])

In [75]:
column_names

array(['age', 'gender', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype=object)

In [77]:
region_index = np.where(column_names == region)[0]
region_index

array([7], dtype=int64)

In [79]:
test_array[0,region_index] = 1

In [21]:
test_array

array([[35. ,  1. , 26.9,  2. ,  0. ,  0. ,  0. ,  0. ,  0. ]])

In [23]:
prediction = linear_model.predict(test_array)[0]
print('Predicted Price is:',np.around(prediction,3))

Predicted Price is: 6463.36


C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
